# Generated by Django 2.0.6 on 2018-08-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('birth_date', models.DateField(null=True)),
                ('number', models.CharField(blank=True, max_length=12)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('img', models.FileField(upload_to='docs/')),
            ],
        ),
        migrations.CreateModel(
            name='AddRe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(blank=True, max_length=100)),
                ('detils', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('up_date', models.DateField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('name_g', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
